INSERT INTO Course VALUES (1,'Computer Science',2);
INSERT INTO Course VALUES (2,'Economics',2);
INSERT INTO Course VALUES (3,'Astrology with French',1);
INSERT INTO Course VALUES (4,'Pure Mathematics with Womens Studies',3);
INSERT INTO Course VALUES (5,'English Literature',4);
INSERT INTO Course VALUES (6,'Geography',3);
INSERT INTO Course VALUES (7,'History of Art',3);
INSERT INTO Course VALUES (8,'Particle Physics',2);
INSERT INTO Course VALUES (9,'Molecular Biology',1);
INSERT INTO Course VALUES (10,'BioEngineering',3);
INSERT INTO Course VALUES (11,'Music',3);
INSERT INTO Course VALUES (12,'History of Music',1);
INSERT INTO Course VALUES (13,'Musical Engineering',1);
INSERT INTO Course VALUES (14,'Musical Chairs',3);
INSERT INTO Course VALUES (15,'Impure Mathematics',4);
INSERT INTO Course VALUES (16,'Astrophysics',2);
INSERT INTO Course VALUES (17,'Astrophysics with German',2);
INSERT INTO Course VALUES (18,'History of Surrey',1);
INSERT INTO Course VALUES (19,'Theatre',2);
INSERT INTO Course VALUES (20,'Psychology',4);
