INSERT INTO Subject VALUES (1,'Intro to Computer Science',3);
INSERT INTO Subject VALUES (2,'Intro to Economics',3);
INSERT INTO Subject VALUES (3,'Intro to Astrology with French',3);
INSERT INTO Subject VALUES (4,'Intro to Pure Mathematics with Womens Studies',1);
INSERT INTO Subject VALUES (5,'Intro to English Literature',1);
INSERT INTO Subject VALUES (6,'Intro to Geography',3);
INSERT INTO Subject VALUES (7,'Intro to History of Art',1);
INSERT INTO Subject VALUES (8,'Intro to Particle Physics',3);
INSERT INTO Subject VALUES (9,'Intro to Molecular Biology',1);
INSERT INTO Subject VALUES (10,'Intro to BioEngineering',2);
INSERT INTO Subject VALUES (11,'Intro to Music',3);
INSERT INTO Subject VALUES (12,'Intro to History of Music',2);
INSERT INTO Subject VALUES (13,'Intro to Musical Engineering',2);
INSERT INTO Subject VALUES (14,'Intro to Musical Chairs',4);
INSERT INTO Subject VALUES (15,'Intro to Impure Mathematics',4);
INSERT INTO Subject VALUES (16,'Intro to Astrophysics',2);
INSERT INTO Subject VALUES (17,'Intro to Astrophysics with German',3);
INSERT INTO Subject VALUES (18,'Intro to History of Surrey',4);
INSERT INTO Subject VALUES (19,'Intro to Theatre',1);
INSERT INTO Subject VALUES (20,'Intro to Psychology',1);
INSERT INTO Subject VALUES (21,'Advanced Computer Science',1);
INSERT INTO Subject VALUES (22,'Advanced Economics',3);
INSERT INTO Subject VALUES (23,'Advanced Astrology with French',2);
INSERT INTO Subject VALUES (24,'Advanced Pure Mathematics with Womens Studies',2);
INSERT INTO Subject VALUES (25,'Advanced English Literature',1);
INSERT INTO Subject VALUES (26,'Advanced Geography',4);
INSERT INTO Subject VALUES (27,'Advanced History of Art',1);
INSERT INTO Subject VALUES (28,'Advanced Particle Physics',3);
INSERT INTO Subject VALUES (29,'Advanced Molecular Biology',3);
INSERT INTO Subject VALUES (30,'Advanced BioEngineering',3);
INSERT INTO Subject VALUES (31,'Advanced Music',2);
INSERT INTO Subject VALUES (32,'Advanced History of Music',3);
INSERT INTO Subject VALUES (33,'Advanced Musical Engineering',4);
INSERT INTO Subject VALUES (34,'Advanced Musical Chairs',1);
INSERT INTO Subject VALUES (35,'Advanced Impure Mathematics',1);
INSERT INTO Subject VALUES (36,'Advanced Astrophysics',1);
INSERT INTO Subject VALUES (37,'Advanced Astrophysics with German',1);
INSERT INTO Subject VALUES (38,'Advanced History of Surrey',3);
INSERT INTO Subject VALUES (39,'Advanced Theatre',4);
INSERT INTO Subject VALUES (40,'Advanced Psychology',4);
INSERT INTO Subject VALUES (41,'MLG Computer Science',1);
INSERT INTO Subject VALUES (42,'MLG Economics',3);
INSERT INTO Subject VALUES (43,'MLG Astrology with French',1);
INSERT INTO Subject VALUES (44,'MLG Pure Mathematics with Womens Studies',4);
INSERT INTO Subject VALUES (45,'MLG English Literature',3);
INSERT INTO Subject VALUES (46,'MLG Geography',3);
INSERT INTO Subject VALUES (47,'MLG History of Art',1);
INSERT INTO Subject VALUES (48,'MLG Particle Physics',3);
INSERT INTO Subject VALUES (49,'MLG Molecular Biology',1);
INSERT INTO Subject VALUES (50,'MLG BioEngineering',3);
INSERT INTO Subject VALUES (51,'MLG Music',2);
INSERT INTO Subject VALUES (52,'MLG History of Music',2);
INSERT INTO Subject VALUES (53,'MLG Musical Engineering',4);
INSERT INTO Subject VALUES (54,'MLG Musical Chairs',1);
INSERT INTO Subject VALUES (55,'MLG Impure Mathematics',3);
INSERT INTO Subject VALUES (56,'MLG Astrophysics',3);
INSERT INTO Subject VALUES (57,'MLG Astrophysics with German',1);
INSERT INTO Subject VALUES (58,'MLG History of Surrey',3);
INSERT INTO Subject VALUES (59,'MLG Theatre',4);
INSERT INTO Subject VALUES (60,'MLG Psychology',2);
